# Generated by Django 4.0.4 on 2022-06-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option5',
            new_name='option1',
        ),
    ]
