# Generated by Django 4.0.4 on 2022-06-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_rename_option5_questions_option1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Exam',
        ),
    ]
